// Export all components from the Partner domain
export { default as PartnerLayout } from './PartnerLayout';
export { default as Dashboard } from './Dashboard';
export { default as Properties } from './Properties';
export { default as Bookings } from './Bookings';
export { default as Maintenances } from './Maintenances';
export { default as Finance } from './Finance';
export { default as Services } from './Services.tsx';
export { default as News } from './News.tsx';
export { default as Amenities } from './Amenities.tsx';
export { default as RoomDetail } from './RoomDetail';
export { default as Calendar } from './Calendar';
export { default as PriceRules } from './PriceRules';
export { default as Chat } from './Chat';
export { default as Reports } from './Reports';
